/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppResumeRouteImport } from './routes/app/resume'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppResumeIndexRouteImport } from './routes/app/resume/index'
import { Route as AppInterviewIndexRouteImport } from './routes/app/interview/index'
import { Route as AppCoverLettersIndexRouteImport } from './routes/app/cover-letters/index'
import { Route as AppResumeIdRouteImport } from './routes/app/resume/$id'
import { Route as AppInterviewMockRouteImport } from './routes/app/interview/mock'
import { Route as AppCoverLettersNewRouteImport } from './routes/app/cover-letters/new'
import { Route as AppCoverLettersIdRouteImport } from './routes/app/cover-letters/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResumeIndexRoute = AppResumeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppResumeRoute,
} as any)
const AppInterviewIndexRoute = AppInterviewIndexRouteImport.update({
  id: '/interview/',
  path: '/interview/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoverLettersIndexRoute = AppCoverLettersIndexRouteImport.update({
  id: '/cover-letters/',
  path: '/cover-letters/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResumeIdRoute = AppResumeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResumeRoute,
} as any)
const AppInterviewMockRoute = AppInterviewMockRouteImport.update({
  id: '/interview/mock',
  path: '/interview/mock',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoverLettersNewRoute = AppCoverLettersNewRouteImport.update({
  id: '/cover-letters/new',
  path: '/cover-letters/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCoverLettersIdRoute = AppCoverLettersIdRouteImport.update({
  id: '/cover-letters/$id',
  path: '/cover-letters/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/resume': typeof AppResumeRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/cover-letters/$id': typeof AppCoverLettersIdRoute
  '/app/cover-letters/new': typeof AppCoverLettersNewRoute
  '/app/interview/mock': typeof AppInterviewMockRoute
  '/app/resume/$id': typeof AppResumeIdRoute
  '/app/cover-letters/': typeof AppCoverLettersIndexRoute
  '/app/interview/': typeof AppInterviewIndexRoute
  '/app/resume/': typeof AppResumeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app': typeof AppIndexRoute
  '/app/cover-letters/$id': typeof AppCoverLettersIdRoute
  '/app/cover-letters/new': typeof AppCoverLettersNewRoute
  '/app/interview/mock': typeof AppInterviewMockRoute
  '/app/resume/$id': typeof AppResumeIdRoute
  '/app/cover-letters': typeof AppCoverLettersIndexRoute
  '/app/interview': typeof AppInterviewIndexRoute
  '/app/resume': typeof AppResumeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/resume': typeof AppResumeRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/': typeof AppIndexRoute
  '/app/cover-letters/$id': typeof AppCoverLettersIdRoute
  '/app/cover-letters/new': typeof AppCoverLettersNewRoute
  '/app/interview/mock': typeof AppInterviewMockRoute
  '/app/resume/$id': typeof AppResumeIdRoute
  '/app/cover-letters/': typeof AppCoverLettersIndexRoute
  '/app/interview/': typeof AppInterviewIndexRoute
  '/app/resume/': typeof AppResumeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/onboarding'
    | '/app/resume'
    | '/app/settings'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/cover-letters/$id'
    | '/app/cover-letters/new'
    | '/app/interview/mock'
    | '/app/resume/$id'
    | '/app/cover-letters/'
    | '/app/interview/'
    | '/app/resume/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/onboarding'
    | '/app/settings'
    | '/auth/login'
    | '/auth/register'
    | '/app'
    | '/app/cover-letters/$id'
    | '/app/cover-letters/new'
    | '/app/interview/mock'
    | '/app/resume/$id'
    | '/app/cover-letters'
    | '/app/interview'
    | '/app/resume'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/onboarding'
    | '/app/resume'
    | '/app/settings'
    | '/auth/login'
    | '/auth/register'
    | '/app/'
    | '/app/cover-letters/$id'
    | '/app/cover-letters/new'
    | '/app/interview/mock'
    | '/app/resume/$id'
    | '/app/cover-letters/'
    | '/app/interview/'
    | '/app/resume/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resume/': {
      id: '/app/resume/'
      path: '/'
      fullPath: '/app/resume/'
      preLoaderRoute: typeof AppResumeIndexRouteImport
      parentRoute: typeof AppResumeRoute
    }
    '/app/interview/': {
      id: '/app/interview/'
      path: '/interview'
      fullPath: '/app/interview/'
      preLoaderRoute: typeof AppInterviewIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cover-letters/': {
      id: '/app/cover-letters/'
      path: '/cover-letters'
      fullPath: '/app/cover-letters/'
      preLoaderRoute: typeof AppCoverLettersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resume/$id': {
      id: '/app/resume/$id'
      path: '/$id'
      fullPath: '/app/resume/$id'
      preLoaderRoute: typeof AppResumeIdRouteImport
      parentRoute: typeof AppResumeRoute
    }
    '/app/interview/mock': {
      id: '/app/interview/mock'
      path: '/interview/mock'
      fullPath: '/app/interview/mock'
      preLoaderRoute: typeof AppInterviewMockRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cover-letters/new': {
      id: '/app/cover-letters/new'
      path: '/cover-letters/new'
      fullPath: '/app/cover-letters/new'
      preLoaderRoute: typeof AppCoverLettersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cover-letters/$id': {
      id: '/app/cover-letters/$id'
      path: '/cover-letters/$id'
      fullPath: '/app/cover-letters/$id'
      preLoaderRoute: typeof AppCoverLettersIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppResumeRouteChildren {
  AppResumeIdRoute: typeof AppResumeIdRoute
  AppResumeIndexRoute: typeof AppResumeIndexRoute
}

const AppResumeRouteChildren: AppResumeRouteChildren = {
  AppResumeIdRoute: AppResumeIdRoute,
  AppResumeIndexRoute: AppResumeIndexRoute,
}

const AppResumeRouteWithChildren = AppResumeRoute._addFileChildren(
  AppResumeRouteChildren,
)

interface AppRouteRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppResumeRoute: typeof AppResumeRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCoverLettersIdRoute: typeof AppCoverLettersIdRoute
  AppCoverLettersNewRoute: typeof AppCoverLettersNewRoute
  AppInterviewMockRoute: typeof AppInterviewMockRoute
  AppCoverLettersIndexRoute: typeof AppCoverLettersIndexRoute
  AppInterviewIndexRoute: typeof AppInterviewIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppResumeRoute: AppResumeRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCoverLettersIdRoute: AppCoverLettersIdRoute,
  AppCoverLettersNewRoute: AppCoverLettersNewRoute,
  AppInterviewMockRoute: AppInterviewMockRoute,
  AppCoverLettersIndexRoute: AppCoverLettersIndexRoute,
  AppInterviewIndexRoute: AppInterviewIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
